[package]
name = "melblkidx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
once_cell = "1.13.0"
rusqlite = "0.27.0"
smol = "1.2.5"
themelio-nodeprot = "0.11.3"
